{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "from sklearn.model_selection import train_test_split, KFold"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "import numpy as np\n",
    "import lightgbm as lgb\n",
    "from sklearn.datasets import load_breast_cancer\n",
    "from sklearn.model_selection import cross_val_score, cross_validate\n",
    "from ray import train, tune, init\n",
    "from ray.tune.schedulers.hb_bohb import HyperBandForBOHB\n",
    "from ray.tune.search.bohb import TuneBOHB\n",
    "from functools import partial\n",
    "from typing import Tuple, Union\n",
    "\n",
    "# Load a sample dataset (you can replace this with your own dataset)\n",
    "data = load_breast_cancer()\n",
    "X, y = data.data, data.target\n",
    "\n",
    "MAX_T = 2\n",
    "\n",
    "# TODO: Model and data and everything need to be somehow predefined\n",
    "# Like in a constant script or something like that.\n",
    "# Maybe we can turn this whole thing into a class and it will be easier? We can save model etc... But so many params\n",
    "\n",
    "\n",
    "def evaluate(model, X, y, cv: int = 5, metric: str = \"accuracy\") -> dict:\n",
    "    cv_scores = cross_validate(\n",
    "        model, X, y, cv=cv, scoring=metric, n_jobs=-1, return_train_score=True\n",
    "    )\n",
    "\n",
    "    # Calculate mean and standard deviation of cross-validation scores\n",
    "    metrics = {\n",
    "        \"mean_score_test\": np.mean(cv_scores[\"test_score\"]),\n",
    "        \"mean_score_train\": np.mean(cv_scores[\"train_score\"]),\n",
    "        \"std_score_test\": np.std(cv_scores[\"test_score\"]),\n",
    "        \"std_score_train\": np.std(cv_scores[\"train_score\"]),\n",
    "        \"std_score_all\": np.std(\n",
    "            np.hstack((cv_scores[\"train_score\"], cv_scores[\"test_score\"]))\n",
    "        ),\n",
    "    }\n",
    "    return metrics\n",
    "\n",
    "\n",
    "# Define the training function\n",
    "def train_lightgbm(\n",
    "    config: dict = {}, loss: str = \"std_overfit_train\", baseline_mean: float = 0.0\n",
    ") -> float:\n",
    "    model = lgb.LGBMClassifier(**config)\n",
    "\n",
    "    metrics = evaluate(model, X, y, cv=5, metric=\"accuracy\")\n",
    "\n",
    "    # TODO: Somehow incorporate baseline as well !\n",
    "    if loss == \"std_overfit_train\":\n",
    "        score = (\n",
    "            np.abs(metrics[\"mean_score_train\"] - metrics[\"mean_score_test\"])\n",
    "            + metrics[\"std_score_all\"]\n",
    "        )\n",
    "    elif loss == \"std_overfit\":\n",
    "        score = (\n",
    "            np.abs(metrics[\"mean_score_train\"] - metrics[\"mean_score_test\"])\n",
    "            + metrics[\"std_score_test\"]\n",
    "        )\n",
    "    elif loss == \"std_train\":\n",
    "        score = metrics[\"std_score_all\"]\n",
    "    elif loss == \"hybrid_std\":\n",
    "        pass\n",
    "    elif loss == \"hybrid_std_overfit\":\n",
    "        score = (\n",
    "            (baseline_mean - metrics[\"mean_score_test\"])  # Minimize\n",
    "            + np.abs(\n",
    "                metrics[\"mean_score_train\"] - metrics[\"mean_score_test\"]\n",
    "            )  # Minimize\n",
    "            + metrics[\"std_score_all\"]  # Minimize\n",
    "        )\n",
    "    elif loss == \"baseline_metric\":\n",
    "        score = baseline_mean - metrics[\"mean_score_test\"]  # Minimize\n",
    "    elif loss == \"metric\":\n",
    "        score = metrics[\"mean_score_test\"]\n",
    "    elif loss == \"hybrid_metric_overfit\":\n",
    "        score = (\n",
    "            np.abs(metrics[\"mean_score_train\"] - metrics[\"mean_score_test\"])\n",
    "            + metrics[\"mean_score_test\"]\n",
    "        )\n",
    "\n",
    "    # Use both mean and std as the metric to minimize\n",
    "    # tune.report(mean_accuracy=mean_score, std_accuracy=std_score)\n",
    "    train.report(score=score)\n",
    "    return score\n",
    "\n",
    "\n",
    "def tune_model(loss: str = \"baseline_metric\") -> Tuple[dict, float]:\n",
    "    \n",
    "    init(num_cpus=6)\n",
    "    \n",
    "    # Define the search space for hyperparameters\n",
    "    config_space = {\n",
    "        \"num_leaves\": tune.choice([20, 30, 40, 50]),\n",
    "        \"learning_rate\": tune.loguniform(1e-4, 1e-1),\n",
    "        \"subsample\": tune.uniform(0.5, 1.0),\n",
    "        \"colsample_bytree\": tune.uniform(0.5, 1.0),\n",
    "        \"reg_alpha\": tune.loguniform(1e-4, 1e2),\n",
    "        \"reg_lambda\": tune.loguniform(1e-4, 1e2),\n",
    "    }\n",
    "\n",
    "    # Define the BOHB scheduler\n",
    "    bohb_hyperband = HyperBandForBOHB(\n",
    "        time_attr=\"training_iteration\", max_t=MAX_T, reduction_factor=2, stop_last_trials=True\n",
    "    )\n",
    "\n",
    "    # Baseline:\n",
    "    # TODO: incorporate baseline loss for every loss function. So that we know what it is like without the baseline and with baseline etc..\n",
    "    baseline_loss = train_lightgbm(loss=loss)\n",
    "    baseline_mean = evaluate(model=lgb.LGBMClassifier(), X=X, y=y)\n",
    "\n",
    "    # Set up the experiment configuration\n",
    "    bohb_search = TuneBOHB(space=config_space, mode=\"min\", metric=\"score\")\n",
    "    bohb_search = tune.search.ConcurrencyLimiter(bohb_search, max_concurrent=4)\n",
    "    fmin_objective = partial(train_lightgbm, loss=loss, baseline_mean=baseline_mean)\n",
    "    analysis = tune.run(\n",
    "        fmin_objective,\n",
    "        # config=config_space,\n",
    "        num_samples=10,  # Number of hyperparameter samples\n",
    "        metric=\"score\",  # Metric to minimize\n",
    "        mode=\"min\",\n",
    "        resources_per_trial={\n",
    "            \"cpu\": 1\n",
    "        },  # Change this to whatever resources you have available\n",
    "        search_alg=bohb_search,\n",
    "        scheduler=bohb_hyperband,\n",
    "        local_dir=\"experiments\",\n",
    "    )\n",
    "\n",
    "    # Get the best hyperparameters\n",
    "    best_config = analysis.get_best_config(metric=\"score\", mode=\"min\")\n",
    "    best_loss = analysis.get_best_logdir(metric=\"score\")\n",
    "    print(\"Best Hyperparameters:\", best_config)\n",
    "    return best_config, best_loss\n",
    "\n",
    "\n",
    "def tune_exp() -> pd.DataFrame:\n",
    "    best_configs = []\n",
    "    best_losses = []\n",
    "    df_metric = pd.DataFrame(\n",
    "        {\n",
    "            \"mean_test\": [],\n",
    "            \"mean_train\": [],\n",
    "            \"std_test\": [],\n",
    "            \"std_train\": [],\n",
    "            \"loss_func\": [],\n",
    "            \"loss\": [],\n",
    "        }\n",
    "    )\n",
    "\n",
    "    losses = [\n",
    "        \"std_overfit_train\",\n",
    "        \"hybrid_std_overfit\",\n",
    "        \"baseline_metric\",\n",
    "        \"hybrid_metric_overfit\",\n",
    "    ]\n",
    "\n",
    "    for loss in losses:\n",
    "        best_config, best_loss = tune_model(loss=loss)\n",
    "        best_configs.append(best_config)\n",
    "        best_losses.append(best_loss)\n",
    "    # Not the most elegant solution.\n",
    "    # Log baseline scores\n",
    "    best_configs.append({})\n",
    "    best_losses.append(\"N/A\")\n",
    "    losses.append(\"BASELINE\")\n",
    "\n",
    "    for idx, config in enumerate(best_configs):\n",
    "        model = lgb.LGBMClassifier(**config)\n",
    "        metrics = evaluate(model, X, y)\n",
    "\n",
    "        metrics[\"loss_func\"] = losses[idx]\n",
    "        metrics[\"loss\"] = best_losses[idx]\n",
    "        del metrics[\"std_all\"]\n",
    "        df_metric = df_metric.append(metrics, ignore_index=True)\n",
    "\n",
    "    return df_metric"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2024-01-02 02:23:47,954\tWARNING bohb_search.py:152 -- You passed a `space` parameter to <class 'ray.tune.search.bohb.bohb_search.TuneBOHB'> that contained unresolved search space definitions. <class 'ray.tune.search.bohb.bohb_search.TuneBOHB'> should however be instantiated with fully configured search spaces only. To use Ray Tune's automatic search space conversion, pass the space definition as part of the `param_space` argument to `tune.Tuner()` instead.\n",
      "2024-01-02 02:23:47,956\tINFO tune.py:583 -- [output] This uses the legacy output and progress reporter, as Jupyter notebooks are not supported by the new engine, yet. For more information, please see https://github.com/ray-project/ray/issues/36949\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<div class=\"tuneStatus\">\n",
       "  <div style=\"display: flex;flex-direction: row\">\n",
       "    <div style=\"display: flex;flex-direction: column;\">\n",
       "      <h3>Tune Status</h3>\n",
       "      <table>\n",
       "<tbody>\n",
       "<tr><td>Current time:</td><td>2024-01-02 02:24:55</td></tr>\n",
       "<tr><td>Running for: </td><td>00:01:07.60        </td></tr>\n",
       "<tr><td>Memory:      </td><td>13.7/13.9 GiB      </td></tr>\n",
       "</tbody>\n",
       "</table>\n",
       "    </div>\n",
       "    <div class=\"vDivider\"></div>\n",
       "    <div class=\"systemInfo\">\n",
       "      <h3>System Info</h3>\n",
       "      Using HyperBand: num_stopped=0 total_brackets=1<br>Round #0:<br>  Bracket(Max Size (n)=1, Milestone (r)=2, completed=100.0%): {ERROR: 10} <br>Logical resource usage: 1.0/12 CPUs, 0/1 GPUs (0.0/1.0 accelerator_type:G)\n",
       "    </div>\n",
       "    <div class=\"vDivider\"></div>\n",
       "<div class=\"messages\">\n",
       "  <h3>Messages</h3>\n",
       "  : ***LOW MEMORY*** less than 10% of the memory on this node is available for use. This can cause unexpected crashes. Consider reducing the memory used by your application or reducing the Ray object store size by setting `object_store_memory` when calling `ray.init`.\n",
       "  \n",
       "  Number of errored trials: 10<br><table>\n",
       "<thead>\n",
       "<tr><th>Trial name             </th><th style=\"text-align: right;\">  # failures</th><th>error file                                                                                                                                                                                                                    </th></tr>\n",
       "</thead>\n",
       "<tbody>\n",
       "<tr><td>train_lightgbm_36c4ea15</td><td style=\"text-align: right;\">           1</td><td>C:/Users/chris/ray_results/train_lightgbm_2024-01-02_02-23-47/train_lightgbm_36c4ea15_1_colsample_bytree=0.9643,learning_rate=0.0127,num_leaves=30,reg_alpha=0.0067,reg_lambda=0.8009,subsample=_2024-01-02_02-23-47\\error.txt</td></tr>\n",
       "<tr><td>train_lightgbm_3e09bda0</td><td style=\"text-align: right;\">           1</td><td>C:/Users/chris/ray_results/train_lightgbm_2024-01-02_02-23-47/train_lightgbm_3e09bda0_2_colsample_bytree=0.7441,learning_rate=0.0019,num_leaves=30,reg_alpha=0.0009,reg_lambda=0.0090,subsample=_2024-01-02_02-23-52\\error.txt</td></tr>\n",
       "<tr><td>train_lightgbm_c1542caf</td><td style=\"text-align: right;\">           1</td><td>C:/Users/chris/ray_results/train_lightgbm_2024-01-02_02-23-47/train_lightgbm_c1542caf_3_colsample_bytree=0.8591,learning_rate=0.0002,num_leaves=20,reg_alpha=0.0051,reg_lambda=0.0004,subsample=_2024-01-02_02-23-58\\error.txt</td></tr>\n",
       "<tr><td>train_lightgbm_1e2c6265</td><td style=\"text-align: right;\">           1</td><td>C:/Users/chris/ray_results/train_lightgbm_2024-01-02_02-23-47/train_lightgbm_1e2c6265_4_colsample_bytree=0.7882,learning_rate=0.0161,num_leaves=20,reg_alpha=7.1416,reg_lambda=0.0185,subsample=_2024-01-02_02-24-03\\error.txt</td></tr>\n",
       "<tr><td>train_lightgbm_fa218678</td><td style=\"text-align: right;\">           1</td><td>C:/Users/chris/ray_results/train_lightgbm_2024-01-02_02-23-47/train_lightgbm_fa218678_5_colsample_bytree=0.9247,learning_rate=0.0086,num_leaves=50,reg_alpha=0.0003,reg_lambda=0.1644,subsample=_2024-01-02_02-24-11\\error.txt</td></tr>\n",
       "<tr><td>train_lightgbm_02597fae</td><td style=\"text-align: right;\">           1</td><td>C:/Users/chris/ray_results/train_lightgbm_2024-01-02_02-23-47/train_lightgbm_02597fae_6_colsample_bytree=0.7557,learning_rate=0.0058,num_leaves=20,reg_alpha=0.0639,reg_lambda=0.0001,subsample=_2024-01-02_02-24-17\\error.txt</td></tr>\n",
       "<tr><td>train_lightgbm_aae3cc9b</td><td style=\"text-align: right;\">           1</td><td>C:/Users/chris/ray_results/train_lightgbm_2024-01-02_02-23-47/train_lightgbm_aae3cc9b_7_colsample_bytree=0.7808,learning_rate=0.0032,num_leaves=30,reg_alpha=0.0002,reg_lambda=1.3518,subsample=_2024-01-02_02-24-24\\error.txt</td></tr>\n",
       "<tr><td>train_lightgbm_306f018b</td><td style=\"text-align: right;\">           1</td><td>C:/Users/chris/ray_results/train_lightgbm_2024-01-02_02-23-47/train_lightgbm_306f018b_8_colsample_bytree=0.5748,learning_rate=0.0129,num_leaves=30,reg_alpha=0.0024,reg_lambda=0.0169,subsample=_2024-01-02_02-24-30\\error.txt</td></tr>\n",
       "<tr><td>train_lightgbm_7348efee</td><td style=\"text-align: right;\">           1</td><td>C:/Users/chris/ray_results/train_lightgbm_2024-01-02_02-23-47/train_lightgbm_7348efee_9_colsample_bytree=0.5223,learning_rate=0.0143,num_leaves=40,reg_alpha=0.7834,reg_lambda=4.3045,subsample=_2024-01-02_02-24-37\\error.txt</td></tr>\n",
       "<tr><td>train_lightgbm_6b0447a6</td><td style=\"text-align: right;\">           1</td><td>C:/Users/chris/ray_results/train_lightgbm_2024-01-02_02-23-47/train_lightgbm_6b0447a6_10_colsample_bytree=0.6807,learning_rate=0.0331,num_leaves=30,reg_alpha=0.0008,reg_lambda=64.8547,subsampl_2024-01-02_02-24-44\\error.txt</td></tr>\n",
       "</tbody>\n",
       "</table>\n",
       "</div>\n",
       "<style>\n",
       ".messages {\n",
       "  color: var(--jp-ui-font-color1);\n",
       "  display: flex;\n",
       "  flex-direction: column;\n",
       "  padding-left: 1em;\n",
       "  overflow-y: auto;\n",
       "}\n",
       ".messages h3 {\n",
       "  font-weight: bold;\n",
       "}\n",
       ".vDivider {\n",
       "  border-left-width: var(--jp-border-width);\n",
       "  border-left-color: var(--jp-border-color0);\n",
       "  border-left-style: solid;\n",
       "  margin: 0.5em 1em 0.5em 1em;\n",
       "}\n",
       "</style>\n",
       "\n",
       "  </div>\n",
       "  <div class=\"hDivider\"></div>\n",
       "  <div class=\"trialStatus\">\n",
       "    <h3>Trial Status</h3>\n",
       "    <table>\n",
       "<thead>\n",
       "<tr><th>Trial name             </th><th>status  </th><th>loc            </th><th style=\"text-align: right;\">  colsample_bytree</th><th style=\"text-align: right;\">  learning_rate</th><th style=\"text-align: right;\">  num_leaves</th><th style=\"text-align: right;\">  reg_alpha</th><th style=\"text-align: right;\">  reg_lambda</th><th style=\"text-align: right;\">  subsample</th></tr>\n",
       "</thead>\n",
       "<tbody>\n",
       "<tr><td>train_lightgbm_36c4ea15</td><td>ERROR   </td><td>127.0.0.1:24604</td><td style=\"text-align: right;\">          0.964325</td><td style=\"text-align: right;\">    0.0126502  </td><td style=\"text-align: right;\">          30</td><td style=\"text-align: right;\">0.0067327  </td><td style=\"text-align: right;\"> 0.800902   </td><td style=\"text-align: right;\">   0.730139</td></tr>\n",
       "<tr><td>train_lightgbm_3e09bda0</td><td>ERROR   </td><td>127.0.0.1:35620</td><td style=\"text-align: right;\">          0.744076</td><td style=\"text-align: right;\">    0.00188466 </td><td style=\"text-align: right;\">          30</td><td style=\"text-align: right;\">0.000944387</td><td style=\"text-align: right;\"> 0.00903944 </td><td style=\"text-align: right;\">   0.744011</td></tr>\n",
       "<tr><td>train_lightgbm_c1542caf</td><td>ERROR   </td><td>127.0.0.1:13792</td><td style=\"text-align: right;\">          0.85912 </td><td style=\"text-align: right;\">    0.000231575</td><td style=\"text-align: right;\">          20</td><td style=\"text-align: right;\">0.0050646  </td><td style=\"text-align: right;\"> 0.000420352</td><td style=\"text-align: right;\">   0.947184</td></tr>\n",
       "<tr><td>train_lightgbm_1e2c6265</td><td>ERROR   </td><td>127.0.0.1:27736</td><td style=\"text-align: right;\">          0.788193</td><td style=\"text-align: right;\">    0.0161023  </td><td style=\"text-align: right;\">          20</td><td style=\"text-align: right;\">7.14156    </td><td style=\"text-align: right;\"> 0.0185497  </td><td style=\"text-align: right;\">   0.589273</td></tr>\n",
       "<tr><td>train_lightgbm_fa218678</td><td>ERROR   </td><td>127.0.0.1:20364</td><td style=\"text-align: right;\">          0.924693</td><td style=\"text-align: right;\">    0.0085792  </td><td style=\"text-align: right;\">          50</td><td style=\"text-align: right;\">0.000328604</td><td style=\"text-align: right;\"> 0.164364   </td><td style=\"text-align: right;\">   0.713718</td></tr>\n",
       "<tr><td>train_lightgbm_02597fae</td><td>ERROR   </td><td>127.0.0.1:38240</td><td style=\"text-align: right;\">          0.755655</td><td style=\"text-align: right;\">    0.00580353 </td><td style=\"text-align: right;\">          20</td><td style=\"text-align: right;\">0.0638635  </td><td style=\"text-align: right;\"> 0.000127723</td><td style=\"text-align: right;\">   0.692384</td></tr>\n",
       "<tr><td>train_lightgbm_aae3cc9b</td><td>ERROR   </td><td>127.0.0.1:15172</td><td style=\"text-align: right;\">          0.780786</td><td style=\"text-align: right;\">    0.00316731 </td><td style=\"text-align: right;\">          30</td><td style=\"text-align: right;\">0.000153809</td><td style=\"text-align: right;\"> 1.35183    </td><td style=\"text-align: right;\">   0.786215</td></tr>\n",
       "<tr><td>train_lightgbm_306f018b</td><td>ERROR   </td><td>127.0.0.1:26812</td><td style=\"text-align: right;\">          0.574762</td><td style=\"text-align: right;\">    0.012899   </td><td style=\"text-align: right;\">          30</td><td style=\"text-align: right;\">0.00241715 </td><td style=\"text-align: right;\"> 0.0168756  </td><td style=\"text-align: right;\">   0.526597</td></tr>\n",
       "<tr><td>train_lightgbm_7348efee</td><td>ERROR   </td><td>127.0.0.1:16908</td><td style=\"text-align: right;\">          0.522286</td><td style=\"text-align: right;\">    0.0142903  </td><td style=\"text-align: right;\">          40</td><td style=\"text-align: right;\">0.783393   </td><td style=\"text-align: right;\"> 4.30455    </td><td style=\"text-align: right;\">   0.828653</td></tr>\n",
       "<tr><td>train_lightgbm_6b0447a6</td><td>ERROR   </td><td>127.0.0.1:40504</td><td style=\"text-align: right;\">          0.680746</td><td style=\"text-align: right;\">    0.0330798  </td><td style=\"text-align: right;\">          30</td><td style=\"text-align: right;\">0.000849314</td><td style=\"text-align: right;\">64.8547     </td><td style=\"text-align: right;\">   0.857485</td></tr>\n",
       "</tbody>\n",
       "</table>\n",
       "  </div>\n",
       "</div>\n",
       "<style>\n",
       ".tuneStatus {\n",
       "  color: var(--jp-ui-font-color1);\n",
       "}\n",
       ".tuneStatus .systemInfo {\n",
       "  display: flex;\n",
       "  flex-direction: column;\n",
       "}\n",
       ".tuneStatus td {\n",
       "  white-space: nowrap;\n",
       "}\n",
       ".tuneStatus .trialStatus {\n",
       "  display: flex;\n",
       "  flex-direction: column;\n",
       "}\n",
       ".tuneStatus h3 {\n",
       "  font-weight: bold;\n",
       "}\n",
       ".tuneStatus .hDivider {\n",
       "  border-bottom-width: var(--jp-border-width);\n",
       "  border-bottom-color: var(--jp-border-color0);\n",
       "  border-bottom-style: solid;\n",
       "}\n",
       ".tuneStatus .vDivider {\n",
       "  border-left-width: var(--jp-border-width);\n",
       "  border-left-color: var(--jp-border-color0);\n",
       "  border-left-style: solid;\n",
       "  margin: 0.5em 1em 0.5em 1em;\n",
       "}\n",
       "</style>\n"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2024-01-02 02:23:56,208\tERROR tune_controller.py:1374 -- Trial task failed for trial train_lightgbm_36c4ea15\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\air\\execution\\_internal\\event_manager.py\", line 110, in resolve_future\n",
      "    result = ray.get(future)\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\_private\\auto_init_hook.py\", line 22, in auto_init_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\_private\\client_mode_hook.py\", line 103, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\_private\\worker.py\", line 2624, in get\n",
      "    raise value.as_instanceof_cause()\n",
      "ray.exceptions.RayTaskError(TypeError): \u001b[36mray::ImplicitFunc.train()\u001b[39m (pid=24604, ip=127.0.0.1, actor_id=633246410d2e42f2b375ee6501000000, repr=func)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1813, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1754, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 467, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\tune\\trainable\\trainable.py\", line 342, in train\n",
      "    raise skipped from exception_cause(skipped)\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\air\\_internal\\util.py\", line 88, in run\n",
      "    self._ret = self._target(*self._args, **self._kwargs)\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\tune\\trainable\\function_trainable.py\", line 115, in <lambda>\n",
      "    training_func=lambda: self._trainable_func(self.config),\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 467, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\tune\\trainable\\function_trainable.py\", line 332, in _trainable_func\n",
      "    output = fn()\n",
      "  File \"C:\\Users\\chris\\AppData\\Local\\Temp\\ipykernel_18216\\3311757129.py\", line 82, in train_lightgbm\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\train\\_internal\\session.py\", line 644, in wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "TypeError: report() got an unexpected keyword argument 'score'\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<div class=\"trialProgress\">\n",
       "  <h3>Trial Progress</h3>\n",
       "  <table>\n",
       "<thead>\n",
       "<tr><th>Trial name             </th></tr>\n",
       "</thead>\n",
       "<tbody>\n",
       "<tr><td>train_lightgbm_02597fae</td></tr>\n",
       "<tr><td>train_lightgbm_1e2c6265</td></tr>\n",
       "<tr><td>train_lightgbm_306f018b</td></tr>\n",
       "<tr><td>train_lightgbm_36c4ea15</td></tr>\n",
       "<tr><td>train_lightgbm_3e09bda0</td></tr>\n",
       "<tr><td>train_lightgbm_6b0447a6</td></tr>\n",
       "<tr><td>train_lightgbm_7348efee</td></tr>\n",
       "<tr><td>train_lightgbm_aae3cc9b</td></tr>\n",
       "<tr><td>train_lightgbm_c1542caf</td></tr>\n",
       "<tr><td>train_lightgbm_fa218678</td></tr>\n",
       "</tbody>\n",
       "</table>\n",
       "</div>\n",
       "<style>\n",
       ".trialProgress {\n",
       "  display: flex;\n",
       "  flex-direction: column;\n",
       "  color: var(--jp-ui-font-color1);\n",
       "}\n",
       ".trialProgress h3 {\n",
       "  font-weight: bold;\n",
       "}\n",
       ".trialProgress td {\n",
       "  white-space: nowrap;\n",
       "}\n",
       "</style>\n"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2024-01-02 02:24:02,043\tERROR tune_controller.py:1374 -- Trial task failed for trial train_lightgbm_3e09bda0\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\air\\execution\\_internal\\event_manager.py\", line 110, in resolve_future\n",
      "    result = ray.get(future)\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\_private\\auto_init_hook.py\", line 22, in auto_init_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\_private\\client_mode_hook.py\", line 103, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\_private\\worker.py\", line 2624, in get\n",
      "    raise value.as_instanceof_cause()\n",
      "ray.exceptions.RayTaskError(TypeError): \u001b[36mray::ImplicitFunc.train()\u001b[39m (pid=35620, ip=127.0.0.1, actor_id=1078422fb3c093feac812b1801000000, repr=func)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1813, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1754, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 467, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\tune\\trainable\\trainable.py\", line 342, in train\n",
      "    raise skipped from exception_cause(skipped)\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\air\\_internal\\util.py\", line 88, in run\n",
      "    self._ret = self._target(*self._args, **self._kwargs)\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\tune\\trainable\\function_trainable.py\", line 115, in <lambda>\n",
      "    training_func=lambda: self._trainable_func(self.config),\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 467, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\tune\\trainable\\function_trainable.py\", line 332, in _trainable_func\n",
      "    output = fn()\n",
      "  File \"C:\\Users\\chris\\AppData\\Local\\Temp\\ipykernel_18216\\3311757129.py\", line 82, in train_lightgbm\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\train\\_internal\\session.py\", line 644, in wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "TypeError: report() got an unexpected keyword argument 'score'\n",
      "2024-01-02 02:24:08,640\tERROR tune_controller.py:1374 -- Trial task failed for trial train_lightgbm_c1542caf\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\air\\execution\\_internal\\event_manager.py\", line 110, in resolve_future\n",
      "    result = ray.get(future)\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\_private\\auto_init_hook.py\", line 22, in auto_init_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\_private\\client_mode_hook.py\", line 103, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\_private\\worker.py\", line 2624, in get\n",
      "    raise value.as_instanceof_cause()\n",
      "ray.exceptions.RayTaskError(TypeError): \u001b[36mray::ImplicitFunc.train()\u001b[39m (pid=13792, ip=127.0.0.1, actor_id=75e656eb0851f3fa5c7160f301000000, repr=func)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1813, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1754, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 467, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\tune\\trainable\\trainable.py\", line 342, in train\n",
      "    raise skipped from exception_cause(skipped)\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\air\\_internal\\util.py\", line 88, in run\n",
      "    self._ret = self._target(*self._args, **self._kwargs)\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\tune\\trainable\\function_trainable.py\", line 115, in <lambda>\n",
      "    training_func=lambda: self._trainable_func(self.config),\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 467, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\tune\\trainable\\function_trainable.py\", line 332, in _trainable_func\n",
      "    output = fn()\n",
      "  File \"C:\\Users\\chris\\AppData\\Local\\Temp\\ipykernel_18216\\3311757129.py\", line 82, in train_lightgbm\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\train\\_internal\\session.py\", line 644, in wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "TypeError: report() got an unexpected keyword argument 'score'\n",
      "2024-01-02 02:24:15,486\tERROR tune_controller.py:1374 -- Trial task failed for trial train_lightgbm_1e2c6265\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\air\\execution\\_internal\\event_manager.py\", line 110, in resolve_future\n",
      "    result = ray.get(future)\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\_private\\auto_init_hook.py\", line 22, in auto_init_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\_private\\client_mode_hook.py\", line 103, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\_private\\worker.py\", line 2624, in get\n",
      "    raise value.as_instanceof_cause()\n",
      "ray.exceptions.RayTaskError(TypeError): \u001b[36mray::ImplicitFunc.train()\u001b[39m (pid=27736, ip=127.0.0.1, actor_id=ae40845ed4ccde7e7bdd656101000000, repr=func)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1813, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1754, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 467, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\tune\\trainable\\trainable.py\", line 342, in train\n",
      "    raise skipped from exception_cause(skipped)\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\air\\_internal\\util.py\", line 88, in run\n",
      "    self._ret = self._target(*self._args, **self._kwargs)\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\tune\\trainable\\function_trainable.py\", line 115, in <lambda>\n",
      "    training_func=lambda: self._trainable_func(self.config),\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 467, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\tune\\trainable\\function_trainable.py\", line 332, in _trainable_func\n",
      "    output = fn()\n",
      "  File \"C:\\Users\\chris\\AppData\\Local\\Temp\\ipykernel_18216\\3311757129.py\", line 82, in train_lightgbm\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\train\\_internal\\session.py\", line 644, in wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "TypeError: report() got an unexpected keyword argument 'score'\n",
      "2024-01-02 02:24:22,102\tERROR tune_controller.py:1374 -- Trial task failed for trial train_lightgbm_fa218678\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\air\\execution\\_internal\\event_manager.py\", line 110, in resolve_future\n",
      "    result = ray.get(future)\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\_private\\auto_init_hook.py\", line 22, in auto_init_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\_private\\client_mode_hook.py\", line 103, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\_private\\worker.py\", line 2624, in get\n",
      "    raise value.as_instanceof_cause()\n",
      "ray.exceptions.RayTaskError(TypeError): \u001b[36mray::ImplicitFunc.train()\u001b[39m (pid=20364, ip=127.0.0.1, actor_id=60d5922ca1f679b8aef2c11701000000, repr=func)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1813, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1754, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 467, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\tune\\trainable\\trainable.py\", line 342, in train\n",
      "    raise skipped from exception_cause(skipped)\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\air\\_internal\\util.py\", line 88, in run\n",
      "    self._ret = self._target(*self._args, **self._kwargs)\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\tune\\trainable\\function_trainable.py\", line 115, in <lambda>\n",
      "    training_func=lambda: self._trainable_func(self.config),\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 467, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\tune\\trainable\\function_trainable.py\", line 332, in _trainable_func\n",
      "    output = fn()\n",
      "  File \"C:\\Users\\chris\\AppData\\Local\\Temp\\ipykernel_18216\\3311757129.py\", line 82, in train_lightgbm\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\train\\_internal\\session.py\", line 644, in wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "TypeError: report() got an unexpected keyword argument 'score'\n",
      "2024-01-02 02:24:28,211\tERROR tune_controller.py:1374 -- Trial task failed for trial train_lightgbm_02597fae\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\air\\execution\\_internal\\event_manager.py\", line 110, in resolve_future\n",
      "    result = ray.get(future)\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\_private\\auto_init_hook.py\", line 22, in auto_init_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\_private\\client_mode_hook.py\", line 103, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\_private\\worker.py\", line 2624, in get\n",
      "    raise value.as_instanceof_cause()\n",
      "ray.exceptions.RayTaskError(TypeError): \u001b[36mray::ImplicitFunc.train()\u001b[39m (pid=38240, ip=127.0.0.1, actor_id=bc82d5aec01376088a81157901000000, repr=func)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1813, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1754, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 467, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\tune\\trainable\\trainable.py\", line 342, in train\n",
      "    raise skipped from exception_cause(skipped)\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\air\\_internal\\util.py\", line 88, in run\n",
      "    self._ret = self._target(*self._args, **self._kwargs)\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\tune\\trainable\\function_trainable.py\", line 115, in <lambda>\n",
      "    training_func=lambda: self._trainable_func(self.config),\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 467, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\tune\\trainable\\function_trainable.py\", line 332, in _trainable_func\n",
      "    output = fn()\n",
      "  File \"C:\\Users\\chris\\AppData\\Local\\Temp\\ipykernel_18216\\3311757129.py\", line 82, in train_lightgbm\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\train\\_internal\\session.py\", line 644, in wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "TypeError: report() got an unexpected keyword argument 'score'\n",
      "2024-01-02 02:24:35,113\tERROR tune_controller.py:1374 -- Trial task failed for trial train_lightgbm_aae3cc9b\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\air\\execution\\_internal\\event_manager.py\", line 110, in resolve_future\n",
      "    result = ray.get(future)\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\_private\\auto_init_hook.py\", line 22, in auto_init_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\_private\\client_mode_hook.py\", line 103, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\_private\\worker.py\", line 2624, in get\n",
      "    raise value.as_instanceof_cause()\n",
      "ray.exceptions.RayTaskError(TypeError): \u001b[36mray::ImplicitFunc.train()\u001b[39m (pid=15172, ip=127.0.0.1, actor_id=7e813617f5bbb172dfecd79501000000, repr=func)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1813, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1754, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 467, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\tune\\trainable\\trainable.py\", line 342, in train\n",
      "    raise skipped from exception_cause(skipped)\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\air\\_internal\\util.py\", line 88, in run\n",
      "    self._ret = self._target(*self._args, **self._kwargs)\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\tune\\trainable\\function_trainable.py\", line 115, in <lambda>\n",
      "    training_func=lambda: self._trainable_func(self.config),\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 467, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\tune\\trainable\\function_trainable.py\", line 332, in _trainable_func\n",
      "    output = fn()\n",
      "  File \"C:\\Users\\chris\\AppData\\Local\\Temp\\ipykernel_18216\\3311757129.py\", line 82, in train_lightgbm\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\train\\_internal\\session.py\", line 644, in wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "TypeError: report() got an unexpected keyword argument 'score'\n",
      "2024-01-02 02:24:42,128\tERROR tune_controller.py:1374 -- Trial task failed for trial train_lightgbm_306f018b\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\air\\execution\\_internal\\event_manager.py\", line 110, in resolve_future\n",
      "    result = ray.get(future)\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\_private\\auto_init_hook.py\", line 22, in auto_init_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\_private\\client_mode_hook.py\", line 103, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\_private\\worker.py\", line 2624, in get\n",
      "    raise value.as_instanceof_cause()\n",
      "ray.exceptions.RayTaskError(TypeError): \u001b[36mray::ImplicitFunc.train()\u001b[39m (pid=26812, ip=127.0.0.1, actor_id=47b1f6e16542324ecb2ef1e101000000, repr=func)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1813, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1754, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 467, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\tune\\trainable\\trainable.py\", line 342, in train\n",
      "    raise skipped from exception_cause(skipped)\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\air\\_internal\\util.py\", line 88, in run\n",
      "    self._ret = self._target(*self._args, **self._kwargs)\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\tune\\trainable\\function_trainable.py\", line 115, in <lambda>\n",
      "    training_func=lambda: self._trainable_func(self.config),\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 467, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\tune\\trainable\\function_trainable.py\", line 332, in _trainable_func\n",
      "    output = fn()\n",
      "  File \"C:\\Users\\chris\\AppData\\Local\\Temp\\ipykernel_18216\\3311757129.py\", line 82, in train_lightgbm\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\train\\_internal\\session.py\", line 644, in wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "TypeError: report() got an unexpected keyword argument 'score'\n",
      "2024-01-02 02:24:48,727\tERROR tune_controller.py:1374 -- Trial task failed for trial train_lightgbm_7348efee\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\air\\execution\\_internal\\event_manager.py\", line 110, in resolve_future\n",
      "    result = ray.get(future)\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\_private\\auto_init_hook.py\", line 22, in auto_init_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\_private\\client_mode_hook.py\", line 103, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\_private\\worker.py\", line 2624, in get\n",
      "    raise value.as_instanceof_cause()\n",
      "ray.exceptions.RayTaskError(TypeError): \u001b[36mray::ImplicitFunc.train()\u001b[39m (pid=16908, ip=127.0.0.1, actor_id=075e5ea804712dfb45ba751101000000, repr=func)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1813, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1754, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 467, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\tune\\trainable\\trainable.py\", line 342, in train\n",
      "    raise skipped from exception_cause(skipped)\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\air\\_internal\\util.py\", line 88, in run\n",
      "    self._ret = self._target(*self._args, **self._kwargs)\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\tune\\trainable\\function_trainable.py\", line 115, in <lambda>\n",
      "    training_func=lambda: self._trainable_func(self.config),\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 467, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\tune\\trainable\\function_trainable.py\", line 332, in _trainable_func\n",
      "    output = fn()\n",
      "  File \"C:\\Users\\chris\\AppData\\Local\\Temp\\ipykernel_18216\\3311757129.py\", line 82, in train_lightgbm\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\train\\_internal\\session.py\", line 644, in wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "TypeError: report() got an unexpected keyword argument 'score'\n",
      "2024-01-02 02:24:55,557\tERROR tune_controller.py:1374 -- Trial task failed for trial train_lightgbm_6b0447a6\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\air\\execution\\_internal\\event_manager.py\", line 110, in resolve_future\n",
      "    result = ray.get(future)\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\_private\\auto_init_hook.py\", line 22, in auto_init_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\_private\\client_mode_hook.py\", line 103, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\_private\\worker.py\", line 2624, in get\n",
      "    raise value.as_instanceof_cause()\n",
      "ray.exceptions.RayTaskError(TypeError): \u001b[36mray::ImplicitFunc.train()\u001b[39m (pid=40504, ip=127.0.0.1, actor_id=989398583be2333ac84c9c3601000000, repr=func)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1813, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1754, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 467, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\tune\\trainable\\trainable.py\", line 342, in train\n",
      "    raise skipped from exception_cause(skipped)\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\air\\_internal\\util.py\", line 88, in run\n",
      "    self._ret = self._target(*self._args, **self._kwargs)\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\tune\\trainable\\function_trainable.py\", line 115, in <lambda>\n",
      "    training_func=lambda: self._trainable_func(self.config),\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 467, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\tune\\trainable\\function_trainable.py\", line 332, in _trainable_func\n",
      "    output = fn()\n",
      "  File \"C:\\Users\\chris\\AppData\\Local\\Temp\\ipykernel_18216\\3311757129.py\", line 82, in train_lightgbm\n",
      "  File \"c:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\train\\_internal\\session.py\", line 644, in wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "TypeError: report() got an unexpected keyword argument 'score'\n"
     ]
    },
    {
     "ename": "TuneError",
     "evalue": "('Trials did not complete', [train_lightgbm_36c4ea15, train_lightgbm_3e09bda0, train_lightgbm_c1542caf, train_lightgbm_1e2c6265, train_lightgbm_fa218678, train_lightgbm_02597fae, train_lightgbm_aae3cc9b, train_lightgbm_306f018b, train_lightgbm_7348efee, train_lightgbm_6b0447a6])",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mTuneError\u001b[0m                                 Traceback (most recent call last)",
      "Cell \u001b[1;32mIn[7], line 1\u001b[0m\n\u001b[1;32m----> 1\u001b[0m df_metric \u001b[38;5;241m=\u001b[39m \u001b[43mtune_exp\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m      2\u001b[0m df_metric\n",
      "Cell \u001b[1;32mIn[6], line 157\u001b[0m, in \u001b[0;36mtune_exp\u001b[1;34m()\u001b[0m\n\u001b[0;32m    149\u001b[0m losses \u001b[38;5;241m=\u001b[39m [\n\u001b[0;32m    150\u001b[0m     \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mstd_overfit_train\u001b[39m\u001b[38;5;124m\"\u001b[39m,\n\u001b[0;32m    151\u001b[0m     \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mhybrid_std_overfit\u001b[39m\u001b[38;5;124m\"\u001b[39m,\n\u001b[0;32m    152\u001b[0m     \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mbaseline_metric\u001b[39m\u001b[38;5;124m\"\u001b[39m,\n\u001b[0;32m    153\u001b[0m     \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mhybrid_metric_overfit\u001b[39m\u001b[38;5;124m\"\u001b[39m,\n\u001b[0;32m    154\u001b[0m ]\n\u001b[0;32m    156\u001b[0m \u001b[38;5;28;01mfor\u001b[39;00m loss \u001b[38;5;129;01min\u001b[39;00m losses:\n\u001b[1;32m--> 157\u001b[0m     best_config, best_loss \u001b[38;5;241m=\u001b[39m \u001b[43mtune_model\u001b[49m\u001b[43m(\u001b[49m\u001b[43mloss\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mloss\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m    158\u001b[0m     best_configs\u001b[38;5;241m.\u001b[39mappend(best_config)\n\u001b[0;32m    159\u001b[0m     best_losses\u001b[38;5;241m.\u001b[39mappend(best_loss)\n",
      "Cell \u001b[1;32mIn[6], line 115\u001b[0m, in \u001b[0;36mtune_model\u001b[1;34m(loss)\u001b[0m\n\u001b[0;32m    113\u001b[0m bohb_search \u001b[38;5;241m=\u001b[39m tune\u001b[38;5;241m.\u001b[39msearch\u001b[38;5;241m.\u001b[39mConcurrencyLimiter(bohb_search, max_concurrent\u001b[38;5;241m=\u001b[39m\u001b[38;5;241m4\u001b[39m)\n\u001b[0;32m    114\u001b[0m fmin_objective \u001b[38;5;241m=\u001b[39m partial(train_lightgbm, loss\u001b[38;5;241m=\u001b[39mloss, baseline_mean\u001b[38;5;241m=\u001b[39mbaseline_mean)\n\u001b[1;32m--> 115\u001b[0m analysis \u001b[38;5;241m=\u001b[39m \u001b[43mtune\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mrun\u001b[49m\u001b[43m(\u001b[49m\n\u001b[0;32m    116\u001b[0m \u001b[43m    \u001b[49m\u001b[43mfmin_objective\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m    117\u001b[0m \u001b[43m    \u001b[49m\u001b[38;5;66;43;03m# config=config_space,\u001b[39;49;00m\n\u001b[0;32m    118\u001b[0m \u001b[43m    \u001b[49m\u001b[43mnum_samples\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;241;43m10\u001b[39;49m\u001b[43m,\u001b[49m\u001b[43m  \u001b[49m\u001b[38;5;66;43;03m# Number of hyperparameter samples\u001b[39;49;00m\n\u001b[0;32m    119\u001b[0m \u001b[43m    \u001b[49m\u001b[43mmetric\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[38;5;124;43mscore\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[43m,\u001b[49m\u001b[43m  \u001b[49m\u001b[38;5;66;43;03m# Metric to minimize\u001b[39;49;00m\n\u001b[0;32m    120\u001b[0m \u001b[43m    \u001b[49m\u001b[43mmode\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[38;5;124;43mmin\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[43m,\u001b[49m\n\u001b[0;32m    121\u001b[0m \u001b[43m    \u001b[49m\u001b[43mresources_per_trial\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43m{\u001b[49m\n\u001b[0;32m    122\u001b[0m \u001b[43m        \u001b[49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[38;5;124;43mcpu\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[43m:\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;241;43m1\u001b[39;49m\n\u001b[0;32m    123\u001b[0m \u001b[43m    \u001b[49m\u001b[43m}\u001b[49m\u001b[43m,\u001b[49m\u001b[43m  \u001b[49m\u001b[38;5;66;43;03m# Change this to whatever resources you have available\u001b[39;49;00m\n\u001b[0;32m    124\u001b[0m \u001b[43m    \u001b[49m\u001b[43msearch_alg\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mbohb_search\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m    125\u001b[0m \u001b[43m    \u001b[49m\u001b[43mscheduler\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mbohb_hyperband\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m    126\u001b[0m \u001b[43m\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m    128\u001b[0m \u001b[38;5;66;03m# Get the best hyperparameters\u001b[39;00m\n\u001b[0;32m    129\u001b[0m best_config \u001b[38;5;241m=\u001b[39m analysis\u001b[38;5;241m.\u001b[39mget_best_config(metric\u001b[38;5;241m=\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mscore\u001b[39m\u001b[38;5;124m\"\u001b[39m, mode\u001b[38;5;241m=\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mmin\u001b[39m\u001b[38;5;124m\"\u001b[39m)\n",
      "File \u001b[1;32mc:\\Users\\chris\\Anaconda3\\envs\\hedno_v2\\lib\\site-packages\\ray\\tune\\tune.py:1036\u001b[0m, in \u001b[0;36mrun\u001b[1;34m(run_or_experiment, name, metric, mode, stop, time_budget_s, config, resources_per_trial, num_samples, storage_path, storage_filesystem, search_alg, scheduler, checkpoint_config, verbose, progress_reporter, log_to_file, trial_name_creator, trial_dirname_creator, sync_config, export_formats, max_failures, fail_fast, restore, resume, reuse_actors, raise_on_failed_trial, callbacks, max_concurrent_trials, keep_checkpoints_num, checkpoint_score_attr, checkpoint_freq, checkpoint_at_end, chdir_to_trial_dir, local_dir, _remote, _remote_string_queue, _entrypoint)\u001b[0m\n\u001b[0;32m   1034\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m incomplete_trials:\n\u001b[0;32m   1035\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m raise_on_failed_trial \u001b[38;5;129;01mand\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m experiment_interrupted_event\u001b[38;5;241m.\u001b[39mis_set():\n\u001b[1;32m-> 1036\u001b[0m         \u001b[38;5;28;01mraise\u001b[39;00m TuneError(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mTrials did not complete\u001b[39m\u001b[38;5;124m\"\u001b[39m, incomplete_trials)\n\u001b[0;32m   1037\u001b[0m     \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[0;32m   1038\u001b[0m         logger\u001b[38;5;241m.\u001b[39merror(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mTrials did not complete: \u001b[39m\u001b[38;5;132;01m%s\u001b[39;00m\u001b[38;5;124m\"\u001b[39m, incomplete_trials)\n",
      "\u001b[1;31mTuneError\u001b[0m: ('Trials did not complete', [train_lightgbm_36c4ea15, train_lightgbm_3e09bda0, train_lightgbm_c1542caf, train_lightgbm_1e2c6265, train_lightgbm_fa218678, train_lightgbm_02597fae, train_lightgbm_aae3cc9b, train_lightgbm_306f018b, train_lightgbm_7348efee, train_lightgbm_6b0447a6])"
     ]
    }
   ],
   "source": [
    "df_metric = tune_exp()\n",
    "df_metric"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 27,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "{'b': [2, 4, 5], 'c': [23, 4, 5]}"
      ]
     },
     "execution_count": 27,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "test_dict = {\n",
    "    \"a\" : [1,2,3],\n",
    "    \"b\" : [2,4,5],\n",
    "    \"c\" : [23,4,5]\n",
    "}\n",
    "\n",
    "del test_dict['a']\n",
    "test_dict"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 26,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "1"
      ]
     },
     "execution_count": 26,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "data = {\"a\": 1, \"b\": 2}\n",
    "\n",
    "data.pop(\"a\", None)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 24,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "start\n",
      "1.0\n",
      "0.9701443875174661\n",
      "0.019240524003817126\n",
      "end\n",
      "0.049096136486351\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "0.049096136486351"
      ]
     },
     "execution_count": 24,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "train_lightgbm(config={})"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "import numpy as np\n",
    "import lightgbm as lgb\n",
    "from sklearn.datasets import load_breast_cancer\n",
    "from sklearn.model_selection import cross_val_score, cross_validate\n",
    "from ray import tune\n",
    "from ray.tune.schedulers import HyperBandForBOHB\n",
    "from functools import partial\n",
    "\n",
    "data = load_breast_cancer()\n",
    "X, y = data.data, data.target\n",
    "\n",
    "model = lgb.LGBMClassifier()\n",
    "\n",
    "cv_scores = cross_validate(\n",
    "    model, X, y, cv=5, scoring=\"accuracy\", n_jobs=-1, return_train_score=True\n",
    ")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "{'fit_time': array([0.12932324, 0.13533711, 0.1248138 , 0.1248138 , 0.13232923]),\n",
       " 'score_time': array([0.00201416, 0.00200152, 0.00300169, 0.00200009, 0.00300789]),\n",
       " 'test_score': array([0.93859649, 0.96491228, 0.98245614, 0.98245614, 0.98230088]),\n",
       " 'train_score': array([1., 1., 1., 1., 1.])}"
      ]
     },
     "execution_count": 4,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "cv_scores"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "array([1., 1., 1., 1., 1.])"
      ]
     },
     "execution_count": 6,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "cv_scores['train_score']"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "np.abs(cv_scores['train_score'] - cv_scores['test_score'])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "array([0.93859649, 0.96491228, 0.98245614, 0.98245614, 0.98230088])"
      ]
     },
     "execution_count": 5,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "cv_scores['test_score']"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "0.985072193758733"
      ]
     },
     "execution_count": 9,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "np.mean(np.hstack((cv_scores[\"train_score\"], cv_scores[\"test_score\"])))"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Get baseline score both for simple scoring metric and for the loss that we are going to create and try to beat that."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Compare multiple loss functions and check accuracy but as well as stability and debugging etc.."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Compare and explain SOTA hyperparameter tuning algorithms and cite sources. Neptune AI explains why but we can cite their sources"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "For model debugging : Morris sensitivity analysis + Partial dependence plots + Permutation Importance + SHAP + Feature importance + DICE"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Partial dependence plots to debug certain features and also to gain insights. We can also plot 2 features to extract insights and also add distributions or histograms or something to show the datapoins and their distribution. Although PDPs have disadvantages, check this article out https://christophm.github.io/interpretable-ml-book/pdp.html"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Protodash for explainability"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Stacking with H20, article etc etc."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Using drift score and prediction drift stuff when training and test splitting to determine best split of data or something like that"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "https://docs.deepchecks.com/stable/tabular/auto_checks/model_evaluation/plot_weak_segments_performance.html#tabular-weak-segments-performance\n",
    "\n",
    "Deepchecks with Weak Segments Performance check"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    " - PiML for model stability with Robustness with feature permutation and metrics change https://selfexplainml.github.io/PiML-Toolbox/_build/html/guides/testing/robustness.html\n",
    " - PiML for reliability https://selfexplainml.github.io/PiML-Toolbox/_build/html/guides/testing/reliability.html\n",
    " - PiML for resilience"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": []
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Brier Score is used to calculate calibration. There might vbe a better alternative"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "hedno_v2",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.16"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
